/**
 * =====================================================
 * JG-SIGAP CONFIG V5
 * Centralized app, database, and role configuration.
 * =====================================================
 */
const CONFIG = {

  APP: {
    NAME: "JG-SIGAP",

    DEV_URL:
      "https://script.google.com/macros/s/AKfycbwjQmDqckJvpbZHf6JUd_9MibJ5OM71F_571h92mz8/dev",

    EXEC_URL:
      "https://script.google.com/macros/s/AKfycbxsqk2okOPyREabWs0GstRlNWZd1rIm8j9JPSP8_Z93vVFGc0zEWdUzCj-tVySgQVgG/exec",

    // true = /dev, false = /exec
    USE_DEV: true,

    DEFAULT_PAGE: "dashboard",
    LOGIN_PAGE: "login"
  },

  SHEET: {
    CONFIG: "00_M_CONFIG",

    USER: "01_M_USER",
    ROLE: "02_M_ROLE",
    DEPARTMENT: "03_M_DEPARTMENT",
    EMPLOYEE: "04_M_EMPLOYEE",
    USER_ROLE: "05_M_USER_ROLE",

    APPROVAL_MATRIX: "06_M_APPROVAL_MATRIX",
    WORKFLOW_STEP: "07_M_WORKFLOW_STEP",
    SLA: "08_M_SLA",
    NUMBERING: "09_M_NUMBERING",

    FPB_HEADER: "10_T_FPB_HEADER",
    FPB_DETAIL: "11_T_FPB_DETAIL",

    UNDERLYING_HEADER: "12_T_UNDERLYING_HEADER",
    UNDERLYING_DETAIL: "13_T_UNDERLYING_DETAIL",
    VENDOR_COMPARISON: "14_T_VENDOR_COMPARISON",

    PP_HEADER: "20_T_PP_HEADER",
    PP_DETAIL: "21_T_PP_DETAIL",
    PP_SOURCE: "22_T_PP_SOURCE",

    PR_HEADER: "30_T_PR_HEADER",
    PR_DETAIL: "31_T_PR_DETAIL",

    PO_HEADER: "40_T_PO_HEADER",
    PO_DETAIL: "41_T_PO_DETAIL",

    RECEIVE_HEADER: "50_T_RECEIVE_HEADER",
    RECEIVE_DETAIL: "51_T_RECEIVE_DETAIL",

    INVOICE_HEADER: "60_T_INVOICE_HEADER",
    INVOICE_DETAIL: "61_T_INVOICE_DETAIL",

    PAYMENT_HEADER: "70_T_PAYMENT_HEADER",
    PAYMENT_DETAIL: "71_T_PAYMENT_DETAIL",

    APPROVAL: "80_T_APPROVAL",
    WORKFLOW_HISTORY: "81_T_WORKFLOW_HISTORY",
    DOCUMENT_LINK: "82_T_DOCUMENT_LINK",
    DOCUMENT_STATUS: "83_T_DOCUMENT_STATUS",
    ITEM_LINK: "84_T_ITEM_LINK",

    AUDIT_LOG: "90_T_AUDIT_LOG",
    NOTIFICATION: "91_T_NOTIFICATION",
    IMPORT_LOG: "92_T_IMPORT_LOG",
    IMPORT_DETAIL: "93_T_IMPORT_DETAIL",
    USER_SESSION: "94_T_USER_SESSION",

    DASHBOARD: "95_R_DASHBOARD",
    R_SLA: "96_R_SLA",
    BOTTLENECK: "97_R_BOTTLENECK",
    R_WORKFLOW: "98_R_WORKFLOW",

    LOADER_CONFIG: "96_M_LOADER_CONFIG",
    LOADER_TEMPLATE: "97_M_LOADER_TEMPLATE",

    SYSTEM_LOG: "99_SYSTEM_LOG"
  },

  ROLE: {
    SUPERADMIN: "SUPERADMIN",
    ADMIN: "ADMIN",
    REQUESTER: "REQUESTER",
    GA_VERIFY: "GA_VERIFY",
    FAT: "FAT",
    IA: "IA",
    PROCUREMENT: "PROCUREMENT",
    WAREHOUSE: "WAREHOUSE",
    FINANCE: "FINANCE",
    MONITORING: "MONITORING"
  }
};

function getAppUrl() {
  return CONFIG.APP.USE_DEV
    ? CONFIG.APP.DEV_URL
    : CONFIG.APP.EXEC_URL;
}

function getAppConfig() {
  return {
    name: CONFIG.APP.NAME,
    appUrl: getAppUrl(),
    devUrl: CONFIG.APP.DEV_URL,
    execUrl: CONFIG.APP.EXEC_URL,
    useDev: CONFIG.APP.USE_DEV,
    defaultPage: CONFIG.APP.DEFAULT_PAGE,
    loginPage: CONFIG.APP.LOGIN_PAGE,
    tokenKey: "JG_SIGAP_TOKEN",
    userKey: "JG_SIGAP_USER",
    roleKey: "JG_SIGAP_ROLE",
    rolesKey: "JG_SIGAP_ROLES"
  };
}
